const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

test('落砂清理四组页面注册并构建到 dist', () => {
  const app = JSON.parse(read('dist/app.json'))
  for (const page of ['list', 'detail', 'shake-report', 'clean-report']) {
    assert.ok(app.pages.includes(`pages/shake-clean/${page}/index`))
    assert.ok(fs.existsSync(path.join(root, `dist/pages/shake-clean/${page}/index.js`)))
    assert.ok(fs.existsSync(path.join(root, `dist/pages/shake-clean/${page}/index.wxml`)))
  }
})

test('首页入口只受独立小程序查看权限控制', () => {
  const source = read('dist/pages/home/index.js')
  const markup = read('dist/pages/home/index.wxml')
  assert.match(source, /mini\.production\.shake_clean\.view/)
  assert.match(markup, /wx:if="\{\{canViewShakeCleanTasks\}\}"/)
  assert.match(markup, /goShakeCleanTasks/)
})

test('列表使用真实分页接口并支持状态、查询、扫码、下拉刷新和加载更多', () => {
  const api = read('dist/services/api.js')
  const source = read('dist/pages/shake-clean/list/index.js')
  const markup = read('dist/pages/shake-clean/list/index.wxml')
  assert.match(api, /\/mini\/production\/shake-clean-tasks/)
  assert.match(source, /onPullDownRefresh/)
  assert.match(source, /onReachBottom/)
  assert.match(source, /scanCode/)
  assert.match(source, /pageSize/)
  assert.match(source, /nextCursor/)
  assert.match(source, /mergeUniqueById/)
  assert.match(source, /result\.records/)
  assert.doesNotMatch(source, /\.sort\(/)
  for (const status of ['WAITING_POURING', 'WAITING_SHAKE', 'SHAKING', 'WAITING_CLEANING', 'CLEANING', 'COMPLETED']) assert.match(source, new RegExp(status))
  assert.match(source, /等待后续浇注/)
  assert.match(markup, /查询/)
  assert.match(markup, /冷却/)
})

test('详情读取 options reports trace defects 且入口只依赖 allowedActions', () => {
  const api = read('dist/services/api.js')
  const source = read('dist/pages/shake-clean/detail/index.js')
  const markup = read('dist/pages/shake-clean/detail/index.wxml')
  for (const endpoint of ['options', 'reports', 'trace', 'defect-options']) assert.match(api, new RegExp(endpoint))
  assert.match(source, /getShakeCleanOptions/)
  assert.match(source, /getShakeCleanReports/)
  assert.match(source, /getShakeCleanTrace/)
  assert.match(source, /getShakeCleanDefects/)
  assert.match(source, /statusLabels/)
  assert.match(source, /等待后续浇注/)
  assert.match(markup, /options\.statusText/)
  assert.doesNotMatch(markup, /options\.executionStatus/)
  assert.match(markup, /allowedActions\.shakeReport/)
  assert.match(markup, /allowedActions\.cleanReport/)
  assert.doesNotMatch(source, /userType|SUPER_ADMIN|供应商|员工/)
  assert.doesNotMatch(markup, /撤销/)
})

test('落砂报工支持设备防错、扫码、快捷数量、缺陷、冷却确认和稳定幂等键', () => {
  const source = read('dist/pages/shake-clean/shake-report/index.js')
  const markup = read('dist/pages/shake-clean/shake-report/index.wxml')
  assert.match(source, /checkShakeClean/)
  assert.match(source, /reportShakeClean/)
  assert.match(source, /EARLY_SHAKE/)
  assert.match(source, /showModal/)
  assert.match(source, /isConflict/)
  assert.match(source, /scanCode/)
  assert.match(source, /equipment\.code === value/)
  assert.match(source, /requestId: makeRequestId\(\)/)
  assert.equal((source.match(/requestId: makeRequestId\(\)/g) || []).length, 1)
  assert.match(source, /scrapQty === 0[\s\S]*defectRows/)
  for (const label of ['-10', '-1', '+1', '+10', '一键拉满', '落砂缺陷']) assert.match(markup, new RegExp(label.replace('+', '\\+')))
  assert.match(markup, /至少 88rpx|field-height-guard/)
})

test('清理报工支持设备防错、扫码、数量、缺陷、浇冒口重量和409就地刷新', () => {
  const source = read('dist/pages/shake-clean/clean-report/index.js')
  const markup = read('dist/pages/shake-clean/clean-report/index.wxml')
  assert.match(source, /reportCleaning/)
  assert.match(source, /isConflict/)
  assert.match(source, /loadOptions/)
  assert.match(source, /scanCode/)
  assert.match(source, /equipment\.code === value/)
  assert.match(source, /batchVersions/)
  assert.match(source, /requestId: makeRequestId\(\)/)
  assert.equal((source.match(/requestId: makeRequestId\(\)/g) || []).length, 1)
  assert.match(source, /scrapQty === 0[\s\S]*defectRows/)
  for (const label of ['-10', '-1', '+1', '+10', '清理缺陷', '切割浇冒口重量']) assert.match(markup, new RegExp(label.replace('+', '\\+')))
  assert.match(markup, /至少 88rpx|field-height-guard/)
})
